### ISSUE TITLE
I am wondering which version of Python to use to run your code 

### ISSUE THREAD

**Issue by NUAAwanghe** [MisakaGeek/RNA-secondary-structure-prediction-by-Capsule-Neural-Network#3]
Dear sir
I am trying to run your code. I am wondering which version of Python I need to use in order to run your code and which libraries I need to use.
Thanks very much!
Best Regards,
He Wang

**Comment by MisakaGeek** [comment]
python 3.7.3

**Comment by MisakaGeek** [comment]
This is our Innovation Training Program. We just start working on it. 
The version of python is 3.7.3.
As for libraries, I'm not sure what you are referring to
